---
- name: Install Cockpit
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cockpit_packages }}"
  tags:
    - cockpit
    - common
    - monitoring

- name: Install Cockpit Webserver
  package:
    name: "{{ cockpit_packages_web}}"
    state: present
  when: cockpit_with_webserver == true
  notify: Enable and Start Cockpit
  tags:
    - cockpit
    - monitoring
    - webserver
