---
- name: Set Cockpit Base to "{{ wtd_cockpit_base_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_cockpit_base_state }}"
  with_items: "{{ wtd_cockpit_base_packages }}"
  tags:
    - cockpit

# Depends on while-true-do.docker
- name: Set Cockpit Docker to "{{ wtd_cockpit_docker_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_cockpit_docker_state }}"
  with_items: "{{ wtd_cockpit_docker_packages }}"
  tags:
    - cockpit
    - docker

# Depends on while-true-do.pcp
- name: Set Cockpit PCP to "{{ wtd_cockpit_pcp_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_cockpit_pcp_state }}"
  with_items: "{{ wtd_cockpit_pcp_packages }}"
  tags:
    - cockpit
    - pcp

# Depends on while-true-do.selinux
- name: Set Cockpit Selinux to "{{ wtd_cockpit_selinux_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_cockpit_selinux_state }}"
  with_items: "{{ wtd_cockpit_selinux_packages }}"
  tags:
    - cockpit
    - selinux

- name: Set Cockpit Webserver to "{{ wtd_cockpit_webserver_state }}"
  include_tasks: "tasks/cockpit-ws.yml"
  when: ( wtd_cockpit_webserver_state == "present" )
  tags:
    - cockpit
    - webserver
    - dashboard
