---
- name: Install Cockpit Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cockpit_packages }}"
  tags:
    - cockpit
    - monitoring

- name: Install Cockpit Selinux Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cockpit_selinux_packages }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - cockpit
    - selinux
    - monitoring

- name: Install Cockpit PCP Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cockpit_pcp_packages }}"
  when: cockpit_with_pcp == True
  tags:
    - cockpit
    - performance
    - monitoring
    - metrics

- name: Install Cockpit Webserver
  package:
    name: "{{ cockpit_packages_web}}"
    state: present
  when: cockpit_with_webserver == true
  notify: Enable and Start Cockpit
  tags:
    - cockpit
    - monitoring
    - webserver
